data:
  kaggle_dataset: 'blastchar/telco-customer-churn'
  dataset_zip: 'telco-customer-churn.zip'
  dataset_csv: 'WA_Fn-UseC_-Telco-Customer-Churn.csv'

model_params:
  xgboost:
    n_estimators: [100, 200, 300,400,500]
    learning_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 4, 5]
    min_child_weight: [1, 3, 5]
    subsample: [0.8, 0.9, 1.0]
    colsample_bytree: [0.8, 0.9, 1.0]

output:
  results_file: 'model_results.txt'
